### ISSUE TITLE
ErrorException: Undefined index: maxLength in vendor/cviebrock/eloquent-sluggable/src/Services/SlugService.php:147

### ISSUE THREAD

**Issue by xoco70** [cviebrock/eloquent-sluggable#321]
Hi, I've just migrated to ^4.1

when composer update, I updated to 4.1.1

Now, I get this error in production. Weird thing is in local, everything is ok, but my production site is broken now :( 

I checked in config/sluggable.php and I have the maxlength field.
I also did: 

`php artisan config:clear`
`php artisan view:clear`
`php artisan cache:clear`

I also deleted manually cache folder.

Any idea why this is happening?

```
[2016-10-17 11:09:52] test.ERROR: ErrorException: Undefined index: maxLength in /home/forge/my.kendozone.com/vendor/cviebrock/eloquent-sluggable/src/Services/SlugService.php:147
Stack trace:
#0 /home/forge/my.kendozone.com/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(36): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/home/forge/my....', 147, Array)
#1 /home/forge/my.kendozone.com/vendor/cviebrock/eloquent-sluggable/src/Services/SlugService.php(147): Raven_Breadcrumbs_ErrorHandler->handleError(8, 'Undefined index...', '/home/forge/my....', 147, Array)
#2 /home/forge/my.kendozone.com/vendor/cviebrock/eloquent-sluggable/src/Services/SlugService.php(84): Cviebrock\EloquentSluggable\Services\SlugService->generateSlug('flordcactus@gma...', Array, 'slug')
#3 /home/forge/my.kendozone.com/vendor/cviebrock/eloquent-sluggable/src/Services/SlugService.php(41): Cviebrock\EloquentSluggable\Services\SlugService->buildSlug('slug', Array, false)
#4 /home/forge/my.kendozone.com/vendor/cviebrock/eloquent-sluggable/src/SluggableObserver.php(57): Cviebrock\EloquentSluggable\Services\SlugService->slug(Object(App\User))
#5 /home/forge/my.kendozone.com/vendor/cviebrock/eloquent-sluggable/src/SluggableObserver.php(43): Cviebrock\EloquentSluggable\SluggableObserver->generateSlug(Object(App\User), 'saving')
#6 [internal function]: Cviebrock\EloquentSluggable\SluggableObserver->saving(Object(App\User))
#7 /home/forge/my.kendozone.com/bootstrap/cache/compiled.php(10127): call_user_func_array(Array, Array)
#8 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(App\User))
#9 /home/forge/my.kendozone.com/bootstrap/cache/compiled.php(10067): call_user_func_array(Object(Closure), Array)
#10 /home/forge/my.kendozone.com/bootstrap/cache/compiled.php(10043): Illuminate\Events\Dispatcher->fire('eloquent.saving...', Array, true)
#11 /home/forge/my.kendozone.com/bootstrap/cache/compiled.php(10822): Illuminate\Events\Dispatcher->until('eloquent.saving...', Object(App\User))
#12 /home/forge/my.kendozone.com/bootstrap/cache/compiled.php(10731): Illuminate\Database\Eloquent\Model->fireModelEvent('eloquent.saving...')
#13 /home/forge/my.kendozone.com/bootstrap/cache/compiled.php(10395): Illuminate\Database\Eloquent\Model->save()
#14 /home/forge/my.kendozone.com/database/seeds/UserSeeder.php(56): Illuminate\Database\Eloquent\Model::create(Array)
#15 /home/forge/my.kendozone.com/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(39): UserSeeder->run()
#16 /home/forge/my.kendozone.com/database/seeds/DatabaseSeeder.php(37): Illuminate\Database\Seeder->call('UserSeeder')
#17 /home/forge/my.kendozone.com/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(63): DatabaseSeeder->run()
#18 /home/forge/my.kendozone.com/bootstrap/cache/compiled.php(11074): Illuminate\Database\Console\Seeds\SeedCommand->Illuminate\Database\Console\Seeds\{closure}()
#19 /home/forge/my.kendozone.com/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(64): Illuminate\Database\Eloquent\Model::unguarded(Object(Closure))
#20 [internal function]: Illuminate\Database\Console\Seeds\SeedCommand->fire()
#21 /home/forge/my.kendozone.com/bootstrap/cache/compiled.php(1272): call_user_func_array(Array, Array)
#22 /home/forge/my.kendozone.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#23 /home/forge/my.kendozone.com/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#24 /home/forge/my.kendozone.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#25 /home/forge/my.kendozone.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(185): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#26 /home/forge/my.kendozone.com/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/RefreshCommand.php(96): Illuminate\Console\Command->call('db:seed', Array)
#27 /home/forge/my.kendozone.com/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/RefreshCommand.php(69): Illuminate\Database\Console\Migrations\RefreshCommand->runSeeder(NULL)
#28 [internal function]: Illuminate\Database\Console\Migrations\RefreshCommand->fire()
#29 /home/forge/my.kendozone.com/bootstrap/cache/compiled.php(1272): call_user_func_array(Array, Array)
#30 /home/forge/my.kendozone.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#31 /home/forge/my.kendozone.com/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /home/forge/my.kendozone.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /home/forge/my.kendozone.com/vendor/symfony/console/Application.php(820): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /home/forge/my.kendozone.com/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\RefreshCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /home/forge/my.kendozone.com/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /home/forge/my.kendozone.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /home/forge/my.kendozone.com/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 {main}  
```

**Comment by cviebrock** [comment]
Did you republish the package configuration? And did you update your models to use the `sluggable()` method instead of the `$sluggable` property?

<https://github.com/cviebrock/eloquent-sluggable/blob/master/UPGRADING.md#upgrading-from-3x-to-4x> has the upgrade details.

**Comment by xoco70** [comment]
Yes, I had to do it in local, and I have it working in local.
So, Yes, I changed the model.

sluggable.php : 

```
<?php

return [
    'build_from' => null,
    'save_to' => 'slug',
    'max_length' => null,
    'method' => null,
    'separator' => '-',
    'unique' => true,
    'include_trashed' => false,
    'on_update' => false,
    'reserved' => null,
];
```

Model: 

```
class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{

    use Authenticatable, Authorizable, CanResetPassword, HasRole, SoftDeletes, Sluggable, AuditingTrait, Notifiable;

/**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'email'
            ]
        ];
    }

//    protected $sluggable = [
//        'build_from' => 'email',
//        'save_to' => 'slug',
//    ];

...
 }
```

**Comment by cviebrock** [comment]
Config key names are now camelCase, not snake_case.  So you should change your sluggable.php accordingly, e.g.:

```
<?php 

return [
    'source' => null,
    'maxLength' => null,
    'method' => null,
    'separator' => '-',
    'unique' => true,
    'includeTrashed' => false,
    'onUpdate' => false,
    'reserved' => null,
];
```

**Comment by xoco70** [comment]
it worked ! Tx for your help! Just don't know why it were working in local...
