### ISSUE TITLE
Laravel 5 support is broken

### ISSUE THREAD

**Issue by vdharshan** [cviebrock/eloquent-sluggable#92]
https://github.com/laravel/framework/issues/6583

**Comment by freekmurze** [comment]
Hi, what's the status on L5 compatibilty?

**Comment by cviebrock** [comment]
Have you tried `dev-develop`?  To be honest, I haven't had a chance to look at this before.  But now that L5 has been released, the plan is to package this up in the next few days.

So, try the `develop` branch and let me know if you have any issues with it.

**Comment by ricardocanelas** [comment]
After install and run 'artisan php' on the terminal

```
exception 'BadMethodCallException' with message 'Call to undefined method [package]' in /MyFolder/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:226
Stack trace:
#0 /MyFolder/vendor/cviebrock/eloquent-sluggable/src/Cviebrock/EloquentSluggable/SluggableServiceProvider.php(22): Illuminate\Support\ServiceProvider->__call('package', Array)
#1 /MyFolder/vendor/cviebrock/eloquent-sluggable/src/Cviebrock/EloquentSluggable/SluggableServiceProvider.php(22): Cviebrock\EloquentSluggable\SluggableServiceProvider->package('cviebrock/eloqu...')
#2 [internal function]: Cviebrock\EloquentSluggable\SluggableServiceProvider->boot()
#3 /MyFolder/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#4 /MyFolder/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(631): Illuminate\Container\Container->call(Array)
#5 /MyFolder/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(613): Illuminate\Foundation\Application->bootProvider(Object(Cviebrock\EloquentSluggable\SluggableServiceProvider))
#6 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Cviebrock\EloquentSluggable\SluggableServiceProvider), 19)
#7 /MyFolder/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(614): array_walk(Array, Object(Closure))
#8 /MyFolder/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
#9 /MyFolder/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(165): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#10 /MyFolder/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(192): Illuminate\Foundation\Application->bootstrapWith(Array)
#11 /MyFolder/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(89): Illuminate\Foundation\Console\Kernel->bootstrap()
#12 /MyFolder/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}
```

my composer.json
```php
"require": {
        "laravel/framework": "5.0.*",
        "illuminate/html": "~5.0",
        "cviebrock/eloquent-sluggable": "dev-develop"
	},
...
```

**Comment by yednotek** [comment]
I get the same error, using the dev-develop branch.

**Comment by ttocskcaj** [comment]
I'm getting the same error. Any news?

**Comment by cviebrock** [comment]
Yeah, I kinda broke it while trying to consolidate everything for L5.   Sorry! :(

Composer is being super slow for me today, but I'm getting it all organized and will try and push up an alpha version for L5 later today.

**Comment by freekmurze** [comment]
nice, looking forward to testing your changes!

**Comment by yednotek** [comment]
That would be awesome! It's one of the final pieces to finish upgrade my project to L5.

**Comment by cviebrock** [comment]
Want to try `dev-master` now?

**Comment by yednotek** [comment]
Hi Colin, I tried it but the slug column in the database remains empty. No
time to debug now unfortunately so perhaps I've made a mistake. Will
investigate tomorrow!

- Owen



2015-02-10 21:05 GMT+01:00 Colin Viebrock <notifications@github.com>:

**Comment by ttocskcaj** [comment]
dev-master seems to work for me now. Did a quick test with a seeder.

**Comment by yednotek** [comment]
Silly me, I had commented out the SluggableServiceProvider in the
configuration. It's working like a charm! Thanks!!

- Owen



2015-02-11 6:47 GMT+01:00 Jack Scott <notifications@github.com>:

**Comment by cviebrock** [comment]
:+1:
